### ISSUE TITLE
Error starting SignalR client host - Engineering tool 

### ISSUE THREAD

**Issue by achu152** [Azure/Industrial-IoT#1031]
Hi ,
we are working on setting up the entire Industrial IIOT package provided by azure 2.7.206 version manually via azure portal due to organization security restriction .However the connection to signalR from engineering tool is failing due to below error . can you please help us in identifying the cause of the error listed here.

##############################################################################################
2021-02-07T11:18:25.041643018Z    at Microsoft.Azure.IIoT.Http.HttpStatusCodeEx.Validate(HttpStatusCode statusCode, String message, Exception inner) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Abstractions\src\Http\Extensions\HttpStatusCodeEx.cs:line 49
2021-02-07T11:18:25.041659518Z    at Microsoft.Azure.IIoT.Http.HttpResponseEx.Validate(IHttpResponse response) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Abstractions\src\Http\Extensions\HttpResponseEx.cs:line 35
2021-02-07T11:18:25.041664418Z    at Microsoft.Azure.IIoT.OpcUa.Api.Registry.Clients.RegistryServiceClient.QueryDiscoverersAsync(DiscovererQueryApiModel query, Nullable`1 pageSize, CancellationToken ct) in D:\a\1\s\api\src\Microsoft.Azure.IIoT.OpcUa.Api.Registry\src\Clients\RegistryServiceClient.cs:line 108
2021-02-07T11:18:25.041668918Z    at Microsoft.Azure.IIoT.App.Services.Registry.GetDiscovererListAsync(PagedResult`1 previousPage) in D:\a\1\s\samples\src\Microsoft.Azure.IIoT.App\src\Services\Registry.cs:line 109
2021-02-07T11:18:25.262596789Z [11:18:25 ERR Microsoft.Azure.IIoT.Http.SignalR.Services.SignalRHubClientHost] Failed to aquire token for hub calling (Platform) - calling without... 

2021-02-07T11:18:27.734108791Z [11:18:27 ERR Microsoft.Azure.IIoT.Http.SignalR.Services.SignalRHubClientHost] Error starting SignalR client host. 
2021-02-07T11:18:27.734160892Z System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
2021-02-07T11:18:27.734888399Z    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2021-02-07T11:18:27.734901999Z    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
2021-02-07T11:18:27.734906199Z    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
2021-02-07T11:18:27.734909699Z    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
2021-02-07T11:18:27.734913299Z    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
2021-02-07T11:18:27.734916899Z    at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
2021-02-07T11:18:27.734920299Z    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
2021-02-07T11:18:27.734928999Z    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
2021-02-07T11:18:27.734932899Z    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
2021-02-07T11:18:27.734936399Z    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
2021-02-07T11:18:27.743058876Z    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
2021-02-07T11:18:27.743073576Z    at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
2021-02-07T11:18:27.743078476Z    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
2021-02-07T11:18:27.743082176Z    at Microsoft.Azure.IIoT.Http.SignalR.Services.SignalRHubClientHost.OpenAsync() in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Services\SignalRHubClientHost.cs:line 166
2021-02-07T11:18:27.743086476Z    at Microsoft.Azure.IIoT.Http.SignalR.Services.SignalRHubClientHost.StartAsync() in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Services\SignalRHubClientHost.cs:line 78
2021-02-07T11:18:27.756173799Z [11:18:27 WRN] Unhandled exception rendering component: Response status code does not indicate success: 400 (Bad Request).
2021-02-07T11:18:27.756188599Z System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
2021-02-07T11:18:27.793977255Z    at Microsoft.Azure.IIoT.Http.SignalR.Services.SignalRHubClientHost.StartAsync() in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Services\SignalRHubClientHost.cs:line 84
2021-02-07T11:18:27.794005756Z    at Microsoft.Azure.IIoT.Http.SignalR.SignalRHubClient.SignalRClientRegistrar.CreateAsync(ISignalRClientConfig config, String endpointUrl, ILogger logger, String resourceId, ITokenProvider provider, IJsonSerializerSettingsProvider jsonSettings) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Client\SignalRHubClient.cs:line 142
2021-02-07T11:18:27.794022456Z    at Microsoft.Azure.IIoT.Http.SignalR.SignalRHubClient.GetHubAsync(String endpointUrl, String resourceId) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Client\SignalRHubClient.cs:line 61
2021-02-07T11:18:27.794026756Z    at Microsoft.Azure.IIoT.OpcUa.Api.Registry.RegistryServiceEvents.SubscribeDiscovererEventsAsync(Func`2 callback) in D:\a\1\s\api\src\Microsoft.Azure.IIoT.OpcUa.Api.Registry\src\Clients\RegistryServiceEvents.cs:line 108
2021-02-07T11:18:27.794030956Z    at Microsoft.Azure.IIoT.App.Pages.Discoverers.OnAfterRenderAsync(Boolean firstRender) in D:\a\1\s\samples\src\Microsoft.Azure.IIoT.App\src\Pages\Discoverers.razor.cs:line 79
2021-02-07T11:18:27.794035056Z    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
2021-02-07T11:18:27.794038456Z [11:18:27 ERR] Unhandled exception in circuit 'E7U7LNdLsKzAUycM0wWPrbrSoXSlz98gyB_GPCzrmbU'.
2021-02-07T11:18:27.794041856Z System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
2021-02-07T11:18:27.794045356Z    at Microsoft.Azure.IIoT.Http.SignalR.Services.SignalRHubClientHost.StartAsync() in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Services\SignalRHubClientHost.cs:line 84
2021-02-07T11:18:27.794049256Z    at Microsoft.Azure.IIoT.Http.SignalR.SignalRHubClient.SignalRClientRegistrar.CreateAsync(ISignalRClientConfig config, String endpointUrl, ILogger logger, String resourceId, ITokenProvider provider, IJsonSerializerSettingsProvider jsonSettings) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Client\SignalRHubClient.cs:line 142
2021-02-07T11:18:27.794054156Z    at Microsoft.Azure.IIoT.Http.SignalR.SignalRHubClient.GetHubAsync(String endpointUrl, String resourceId) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Http.SignalR\src\Client\SignalRHubClient.cs:line 61
2021-02-07T11:18:27.794058156Z    at Microsoft.Azure.IIoT.OpcUa.Api.Registry.RegistryServiceEvents.SubscribeDiscovererEventsAsync(Func`2 callback) in D:\a\1\s\api\src\Microsoft.Azure.IIoT.OpcUa.Api.Registry\src\Clients\RegistryServiceEvents.cs:line 108
2021-02-07T11:18:27.794062156Z    at Microsoft.Azure.IIoT.App.Pages.Discoverers.OnAfterRenderAsync(Boolean firstRender) in D:\a\1\s\samples\src\Microsoft.Azure.IIoT.App\src\Pages\Discoverers.razor.cs:line 79
2021-02-07T11:18:27.794065956Z    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
2021-02-07T11:18:28.109857530Z [11:18:28 INF] Executed endpoint '/_blazor'
##############################################################################################

**Comment by hansgschossmann** [comment]
The manual deployment is not a supported scenario. Please use the deploy script or the IAI deployment option to get the Industrial-IoT platform deployed.

Closing this issue for now.
