### ISSUE TITLE
OPC Publisher: System.ObjectDisposedException: Cannot access a disposed object on a System.Threading.Timer

### ISSUE THREAD

**Issue by derSchtefan** [Azure/Industrial-IoT#1169]
**Describe the bug**
Always when the OPC Publisher is starting up after a new or a changing IoT Edge deployment, it crashes with a "System.ObjectDisposedException: Cannot access a disposed object." exception on a System.Threading.Timer.

It seems that a startup and a termination event occurs at the same time, crashing the module, and preventing any restart logic from happening. The module then simply hangs dead in the water.

!! See comment for potential fix

**To Reproduce**

Deploy a new IoT edge solution with the standalone OPC Publisher on a fresh edge device. There is a very high chance you will run into the issue.

Command line: 
```
    "--aa",
                    "--to",
                    "--tm",
                    "--loglevel=information",
                    "--fetchdisplayname=true",
                    "--pf=/appdata/publishednodes.json",
                    "--di=60",
                    "--fm=true",
                    "--si=1"
```

**Expected behavior**
No exception or at least a clean module restart.

**Screenshots**
```
[2021-05-10 10:38:22Z INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Connecting all clients to XXXXXXX.rconnect.lan using MqttOverTcp.
[2021-05-10 10:38:23Z INF Root] Starting module OpcPublisher version 2.8.
[2021-05-10 10:38:23Z INF Root] Initiating prometheus at port 9702/metrics
[2021-05-10 10:38:23Z INF Root] Prometheus metric server started.
opcstacktracemask set to: 0x0
[2021-05-10 10:38:23Z WRN Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Bypassing certificate validation for client.
[2021-05-10 10:38:23Z INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] Running in iotedge context.
[2021-05-10 10:38:28Z INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] 0: Module XXXXXXXXXXXX_OPCPublisher disconnected due to Retry_Expired - now Disconnected...
[2021-05-10 10:39:08Z INF Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory] 0: Module XXXXXXXXXXXX_OPCPublisher reconnected due to Connection_Ok.
[2021-05-10 10:39:11Z INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Initialize device twin for XXXXXXXXXXXX - OPCPublisher
[2021-05-10 10:39:12Z INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Applying initial desired state.
[2021-05-10 10:39:12Z INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Reporting currently initial state.
[2021-05-10 10:39:13Z INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] Module Host started.
[2021-05-10 10:39:13Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] File /appdata/publishednodes.json has changed, last known hash null, new hash 1FA44C537A478A295CF634E0FD727932ADC0C3B0CE441AA84C817F4597034169, reloading...
[2021-05-10 10:39:13Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Models.PublishedNodesJobConverter] Read 5 items from published nodes file in 00:00:00.3377635
[2021-05-10 10:39:14Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Models.PublishedNodesJobConverter] Converted items to jobs in 00:00:00.5097894
[2021-05-10 10:39:14Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] Job opc.tcp://192.168.1.131:4841/XXUnitServer_c117a8ecf9270b256fa746035cc6da440d64cd42 loaded. DataSetWriters endpoints: opc.tcp://192.168.1.131:4841/XXUnitServer
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] Job opc.tcp://192.168.1.131:4840/XXUnitServer_f48c48babe63fb83e0d38da668724789a47f910a loaded. DataSetWriters endpoints: opc.tcp://192.168.1.131:4840/XXUnitServer
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] Job opc.tcp://10.1.25.7:62511/XXXXX.Opc.Demo.SimulationServer_535ff5f484d6cea9ef025d177347bf0011f74631 loaded. DataSetWriters endpoints: opc.tcp://10.1.25.7:62511/XXXXX.Opc.Demo.SimulationServer
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] Job opc.tcp://10.1.25.7:62521/XXXXX.Opc.Demo.SimulationServer_1e699704ba456814400c3cd1acbeac239676bed3 loaded. DataSetWriters endpoints: opc.tcp://10.1.25.7:62521/XXXXX.Opc.Demo.SimulationServer
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] Job opc.tcp://10.1.25.7:62531/XXXXX.Opc.Demo.SimulationServer_0937480174309e591b91a5ea90401fdac2dad0c3 loaded. DataSetWriters endpoints: opc.tcp://10.1.25.7:62531/XXXXX.Opc.Demo.SimulationServer
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.LegacyJobOrchestrator] Thread pool changed to: worker 5, async 5 threads succeeded
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Creating new worker with id StandalonePublisher_0
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Starting worker 'StandalonePublisher_0'...
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Worker StandalonePublisher_0: {}
[2021-05-10 10:39:15Z INF Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Worker: StandalonePublisher_0 processing job: opc.tcp://192.168.1.131:4841/XXUnitServer_c117a8ecf9270b256fa746035cc6da440d64cd42, mode: Active
[2021-05-10 10:39:17Z INF Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] OPC UA security configuration minimum certificate key size is 1024
[2021-05-10 10:39:17Z INF Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] OPC UA security configuration nonce length is 32
[2021-05-10 10:39:17Z WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] OPC UA security configuration is set to accept SHA1 signed peer certificates
[2021-05-10 10:39:17Z WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] OPC UA security configuration is set to auto accept untrusted peer certificates
[2021-05-10 10:39:17Z WRN Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager] OPC UA security configuration is set to accept certificates having an unknown revocation status
[2021-05-10 10:39:17Z INF Root] Module reset...
[2021-05-10 10:39:17Z INF Microsoft.Azure.IIoT.Agent.Framework.Agent.WorkerSupervisor] Stopping worker supervisor
[2021-05-10 10:39:17Z INF Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Stopping worker...
[2021-05-10 10:39:17Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.DataFlowProcessingEngine] Max. egress message queue: 4096 messages (1024 MB)
[2021-05-10 10:39:18Z INF Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker] Processing cancellation received ...
[2021-05-10 10:39:18Z ERR Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker+JobProcess] Error processing job opc.tcp://192.168.1.131:4841/XXUnitServer_c117a8ecf9270b256fa746035cc6da440d64cd42.
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
   at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
   at Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker.JobProcess.ProcessAsync() in /src/common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/Worker.cs:line 350
```

**Desktop (please complete the following information):**
- IoT Edge 1.1 
- Publisher version from dcd7a4a57d6e0e25936769f1496d687626d1f282  (but quick code analysis shows the code in question is probably identical to the latest version on master branch)

**Comment by derSchtefan** [comment]
I looked into this and I think the debugger info of line 350 is slightly misleading, but I can see that in /src/Agent/Default/Worker.cs line 348 a ".Change" call occurs. If at that point the Timer is already disposed (for whatever reason), and the call throws an ObjectDisposed error, the `finally` block nevertheless will try to call ".Change" in line 367, and CleanupAsync won't be called, the exception bubbling up in an uncontrolled fashion.

Is this the source of the problem?
