### ISSUE TITLE
System.InvalidOperationException: Subscriber list is modified while subscriptions are removed

### ISSUE THREAD

**Issue by mregen** [Azure/Industrial-IoT#1333]
**Describe the bug**
Publisher imposes exception in the Opc.Ua.Client because a list with subscriptions which is passed in an API is modified while the  client API processes it.

**To Reproduce**
1. Start publisher, publish
2. Restart a OPC Server from which data is being published
3. Eventually exception is hit

**Expected behavior**
- No Exception, no lists are modified while external APIs are called

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: latest main

**Additional context**
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Opc.Ua.Client.Session.RemoveSubscriptions(IEnumerable`1 subscriptions) in /_/Libraries/Opc.Ua.Client/Session.cs:line 3346
```

```
[External Code]
Opc.Ua.Client.dll!Opc.Ua.Client.Session.RemoveSubscriptions(System.Collections.Generic.IEnumerable<Opc.Ua.Client.Subscription> subscriptions) Line 3346
	at /_/Libraries/Opc.Ua.Client/Session.cs(3346)
Microsoft.Azure.IIoT.OpcUa.Protocol.dll!Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager.HandleRetryAsync.AnonymousMethod__0() Line 354
	at \Industrial-IoT\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Protocol\src\Services\DefaultSessionManager.cs(354)
Microsoft.Azure.IIoT.Core.dll!Microsoft.Azure.IIoT.Utils.Try.Op<bool>(System.Func<bool> action) Line 39
	at \Industrial-IoT\common\src\Microsoft.Azure.IIoT.Core\src\Utils\Try.cs(39)
Microsoft.Azure.IIoT.OpcUa.Protocol.dll!Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager.HandleRetryAsync(Microsoft.Azure.IIoT.OpcUa.Protocol.Models.ConnectionIdentifier id, Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager.SessionWrapper wrapper, System.Threading.CancellationToken ct) Line 354
	at \Industrial-IoT\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Protocol\src\Services\DefaultSessionManager.cs(354)
Microsoft.Azure.IIoT.OpcUa.Protocol.dll!Microsoft.Azure.IIoT.OpcUa.Protocol.Services.DefaultSessionManager.RunAsync.AnonymousMethod__2() Line 245
	at \Industrial-IoT\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Protocol\src\Services\DefaultSessionManager.cs(245)
[External Code]
```

**Comment by dacolgit** [comment]
Closed because the bug is not reproducible.
Please reopen if you find it again, with detailed instructions on how to reproduce it..
