### ISSUE TITLE
Multiple Requests to IBrowseServices<EndpointRegistrationModel>.NodeBrowseAsync result in exception

### ISSUE THREAD

**Issue by mma-mm** [Azure/Industrial-IoT#15]
Hi,

I'm using the supervisor client to access the opc device twin module from my module. I need to Browse multiple nodes, so i start several Tasks with NodeBrowseAsync at once. This sometimes works, sometimes it results in this Exception:

    Microsoft.Azure.Devices.Client.Exceptions.IotHubException: {"message":"Timed out waiting for device to respond to method request 9aabd6bb-d1a9-47ac-833f-ac040cb53b5f","exceptionMessage":"","status":0,"payload":null}
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.ModuleClient.InvokeMethodAsync(Uri uri, MethodRequest methodRequest, CancellationToken cancellationToken)
       at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.CallMethodAsync(String deviceId, String moduleId, String method, String payload, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.Default.ChunkMethodClient.CallMethodAsync(String deviceId, String moduleId, String method, Byte[] payload, String contentType, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.MethodClientEx.CallMethodAsync(IMethodClient client, String deviceId, String moduleId, String method, String json, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.CallServiceOnSupervisor[T,R](String service, EndpointRegistrationModel registration, T request)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.NodeValueReadAsync(EndpointRegistrationModel registration, ValueReadRequestModel request)
       at MyModule.Communication.Twincommunicator.GetValue(String nodeId)

Once this exception appears, it will appear for about a minute for any browse request or read request made. If some time passes until the next request, it works again.

Is there a limit, how many BrowseOperations can be queued or run in parallel or per second? If so, what is the limit?
The connection is made over the edge hub, so i don't think IoT-Hub-Throttling applies.
I don't think hardware is limiting here, due to 4 cores and 8GB RAM.

Edit:
The log of the edgeHub indicates, that the opc device twin doesn't answer (in time).

    2019-04-18 07:13:46.053 +00:00 [INF] - Request starting HTTP/1.1 POST https://ubuntu/twins/linux-test-device/modules/opc-device-twin-module/methods?api-version=2018-06-30 application/json; charset=utf-8 542
    2019-04-18 07:13:46.054 +00:00 [INF] - Client linux-test-device/my-module in device scope authenticated locally.
    2019-04-18 07:13:46.054 +00:00 [INF] - Route matched with "{action = \"InvokeModuleMethodAsync\", controller = \"Twins\"}". Executing action "Microsoft.Azure.Devices.Edge.Hub.Http.Controllers.TwinsController.InvokeModuleMethodAsync (Microsoft.Azure.Devices.Edge.Hub.Http)"
    2019-04-18 07:13:46.055 +00:00 [INF] - Executing action method "Microsoft.Azure.Devices.Edge.Hub.Http.Controllers.TwinsController.InvokeModuleMethodAsync (Microsoft.Azure.Devices.Edge.Hub.Http)" with arguments (["linux-test-device", "opc-device-twin-module", "Microsoft.Azure.Devices.Edge.Hub.Http.MethodRequest"]) - Validation state: Valid
    2019-04-18 07:14:16.061 +00:00 [WRN] - Did not receive response for method invoke call from device/module linux-test-device/opc-device-twin-module for linux-test-device/opc-device-twin-module with correlation ID a6bc8397-e99f-43ff-b0c5-6c0940d7749c
    2019-04-18 07:14:16.066 +00:00 [INF] - Executed action method "Microsoft.Azure.Devices.Edge.Hub.Http.Controllers.TwinsController.InvokeModuleMethodAsync (Microsoft.Azure.Devices.Edge.Hub.Http)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 30011.0176ms.
    2019-04-18 07:14:16.066 +00:00 [INF] - Executing ObjectResult, writing value of type '"Microsoft.Azure.Devices.Edge.Hub.Http.MethodErrorResult"'.
    2019-04-18 07:14:16.070 +00:00 [INF] - Executed action "Microsoft.Azure.Devices.Edge.Hub.Http.Controllers.TwinsController.InvokeModuleMethodAsync (Microsoft.Azure.Devices.Edge.Hub.Http)" in 30015.5847ms
    2019-04-18 07:14:16.070 +00:00 [INF] - Request finished in 30016.5999ms 504 application/json; charset=utf-8

Thanks for your help

Matthias Mucha

**Comment by cristipogacean** [comment]
Hi Matthias, as you probably noticed, we did quite intensive development and refactoring in the platform lately. We have not been able to replicate the issue lately, therefore we would kindly ask you to try to replicate it with the actual master branch and provide some us feedback on the results.
