### ISSUE TITLE
Error during module execution inside IoT Edge

### ISSUE THREAD

**Issue by tbn-mm** [Azure/Industrial-IoT#16]
I tried to run the module inside IoT Edge without the EdgeHubConnectionString as argument, but I get the following exception:

```
[11:28:46 DBG] Starting Module Host...
[11:28:46 ERR] Error during module execution - restarting!
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.<>c__DisplayClass5_0.<CreateAsync>b__0(ConnectionStatus s, ConnectionStatusChangeReason r)
   at Microsoft.Azure.Devices.Client.InternalClient.OnConnectionStatusChanged(ConnectionStatus status, ConnectionStatusChangeReason reason)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.CreateAsync(String product, IotHubConnectionStringBuilder cs, ITransportSettings transportSetting, TimeSpan timeout, IRetryPolicy retry, Action onConnectionLost, ILogger logger)
   at Microsoft.Azure.IIoT.Utils.Try.Options[T](Func`1[] options)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String serviceInfo, IProcessControl reset)
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.ModuleProcess.RunAsync() in /src/src/ModuleProcess.cs:line 93
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.<>c__DisplayClass5_0.<CreateAsync>b__0(ConnectionStatus s, ConnectionStatusChangeReason r)
   at Microsoft.Azure.Devices.Client.InternalClient.OnConnectionStatusChanged(ConnectionStatus status, ConnectionStatusChangeReason reason)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.CreateAsync(String product, IotHubConnectionStringBuilder cs, ITransportSettings transportSetting, TimeSpan timeout, IRetryPolicy retry, Action onConnectionLost, ILogger logger)
   at Microsoft.Azure.IIoT.Utils.Try.Options[T](Func`1[] options)<---

```

It's running on Linux amd64 and the latest mschier_develop (master or tag 2.0.0 doesn't compile: 'LogEx' does not contain a definition for 'Level'). It's running when I set cmd EdgeHubConnectionString (which is the module connection string, not edgehub)

**Comment by marcschier** [comment]
In 2.5.1
