### ISSUE TITLE
azure-iiot-opc-twin-module stops responding to requests

### ISSUE THREAD

**Issue by mma-mm** [Azure/Industrial-IoT#18]
Hi,

i'm using the opc-twin-module to browse an opc-server from another edge module using the supervisorclient of azure-iiot-opc-ua. 
Sometimes the opc twin module stops responding to direct method calls, so an IoTHubException is thrown:

    Microsoft.Azure.Devices.Client.Exceptions.IotHubException: {"message":"Timed out waiting for device to respond to method request 9aabd6bb-d1a9-47ac-833f-ac040cb53b5f","exceptionMessage":"","status":0,"payload":null}
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.ModuleClient.InvokeMethodAsync(Uri uri, MethodRequest methodRequest, CancellationToken cancellationToken)
       at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.CallMethodAsync(String deviceId, String moduleId, String method, String payload, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.Default.ChunkMethodClient.CallMethodAsync(String deviceId, String moduleId, String method, Byte[] payload, String contentType, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.MethodClientEx.CallMethodAsync(IMethodClient client, String deviceId, String moduleId, String method, String json, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.CallServiceOnSupervisor[T,R](String service, EndpointRegistrationModel registration, T request)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.NodeValueReadAsync(EndpointRegistrationModel registration, ValueReadRequestModel request)
       at MyModule.Communication.Twincommunicator.GetValue(String nodeId)

This is the same issue as [this one](https://github.com/Azure/azure-iiot-opc-ua/issues/5), the root cause seems to be in the opc-twin-module.

**Comment by marcschier** [comment]
We now have long running browse and activation tests.  We have not seen this and believe this was caused by bugs in the ask version used in the original twin.  Please reopen if you see this issue again.
