### ISSUE TITLE
Discovery module not connecting

### ISSUE THREAD

**Issue by ghost** [Azure/Industrial-IoT#1842]
**Describe the bug**
When deploying the Discovery module to the edge gateway, it starts, but fails to connect and logs the following error message: "Module [deviceId]_discovery disconnected due to Communication_Error - now Disconnected_Retrying...".

**To Reproduce**
1. Deploy module with following create options:
```
{
  "Hostname": "discovery",
  "Cmd": [
    "PkiRootPath=/mount/pki"
  ],
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  },
  "HostConfig": {
    "NetworkMode": "host",
    "Binds": [
      "/home/iotedge-user/mount:/mount"
    ],
    "CapDrop": [
      "CHOWN",
      "SETUID"
    ]
  }
}
```
2. Check logs.

**Expected behavior**
I expect the module to connect and to allow discovery of an OPC UA server (KepServerEx) running locally on the windows host device.

**Screenshots**
This is what the architecture looks like. What I want is for the discovery module to be able to discover the kepserver.
![architecture](https://user-images.githubusercontent.com/112931842/195813648-f2954c32-900d-4c12-bda0-c5a5246a099e.png)

**EFLOW host:**
 - OS: Windows 11

**EFLOW vm:**
 - OS: CBL-Mariner/Linux

**Discovery module:**
 - Image URI: mcr.microsoft.com/iotedge/discovery:2.8
 - Version: 2.8

**Added info**
The EFLOW vm is currently set up to use the default switch (internal).

**Comment by marcschier** [comment]
I think this will be related to host mode, remove host network mode and try to deploy again.  It should then find the edgehub. 
 Since EEFLOW runs in a vm with switch host mode is not necessary anyway, but you need to define the scan network mask then (like in the windows instructions).

**Comment by ghost** [comment]
Okay so I removed the host mode part and deployed it with following create options
```
{
  "Hostname": "discovery",
  "Cmd": [
    "PkiRootPath=/mount/pki"
  ],
  "HostConfig": {
    "Binds": [
      "/home/iotedge-user/mount:/mount"
    ],
    "CapDrop": [
      "CHOWN",
      "SETUID"
    ]
  }
}
```
The module actually connects now and it shows up in the Asset Discovery view in the Engineering Tool. I do notice another problem now. My OPC UA server endpoint is at "opc.tcp://10.1.67.169:49320", so in the Effective Configuration for the discovery I updated the 'Mask Address Range' field to 10.1.67.0/24. I left all other values on default. When I turn on the scanning however some logs get printed, but no endpoints are discovered and after a few seconds the discovery module seems to disconnect.

When I check the logs for the discovery module it says the following:
```
[2022-10-14 13:54:29.103 INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] New settings processed. 
[2022-10-14 13:54:29.104 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Discovery operation started. 
[2022-10-14 13:54:29.139 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Start Fast discovery run... 
[2022-10-14 13:54:29.139 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Starting network scan (0 probes active)... 
[2022-10-14 13:54:29.146 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Start scanning ["10.1.67.0/24"]... 
[2022-10-14 13:54:29.174 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.123 (0 scanned)... 
[2022-10-14 13:54:29.175 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.12 (0 scanned)... 
[2022-10-14 13:54:29.177 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.176 (1 scanned)... 
[2022-10-14 13:54:29.177 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.248 (2 scanned)... 
[2022-10-14 13:54:29.177 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.251 (3 scanned)... 
[2022-10-14 13:54:29.177 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.252 (4 scanned)... 
[2022-10-14 13:54:29.177 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.47 (5 scanned)... 
[2022-10-14 13:54:29.177 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.141 (6 scanned)... 
[2022-10-14 13:54:29.178 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.170 (7 scanned)... 
[2022-10-14 13:54:29.178 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.126 (8 scanned)... 
[2022-10-14 13:54:29.178 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.37 (9 scanned)... 
[2022-10-14 13:54:29.179 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.45 (10 scanned)... 
[2022-10-14 13:54:29.179 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.14 (11 scanned)... 
[2022-10-14 13:54:29.179 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.177 (12 scanned)... 
[2022-10-14 13:54:29.181 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.115 (14 scanned)... 
[2022-10-14 13:54:29.181 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.164 (15 scanned)... 
[2022-10-14 13:54:29.182 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.17 (16 scanned)... 
[2022-10-14 13:54:29.208 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.167 (17 scanned)... 
[2022-10-14 13:54:29.211 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.143 (18 scanned)... 
[2022-10-14 13:54:29.232 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.117 (19 scanned)... 
[2022-10-14 13:54:29.238 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.154 (20 scanned)... 
[2022-10-14 13:54:29.248 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.44 (21 scanned)... 
[2022-10-14 13:54:29.249 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.173 (22 scanned)... 
[2022-10-14 13:54:29.305 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.53 (23 scanned)... 
[2022-10-14 13:54:30.005 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.3 (24 scanned)... 
[2022-10-14 13:54:32.177 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.36 (110 scanned)... 
[2022-10-14 13:54:32.182 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.24 (111 scanned)... 
[2022-10-14 13:54:32.182 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.145 (112 scanned)... 
[2022-10-14 13:54:32.182 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.32 (113 scanned)... 
[2022-10-14 13:54:32.182 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.161 (114 scanned)... 
[2022-10-14 13:54:32.183 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.55 (115 scanned)... 
[2022-10-14 13:54:32.183 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.124 (116 scanned)... 
[2022-10-14 13:54:32.183 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.18 (117 scanned)... 
[2022-10-14 13:54:32.184 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.160 (118 scanned)... 
[2022-10-14 13:54:32.184 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.35 (119 scanned)... 
[2022-10-14 13:54:32.184 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.49 (120 scanned)... 
[2022-10-14 13:54:32.184 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.247 (120 scanned)... 
[2022-10-14 13:54:32.186 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.9 (129 scanned)... 
[2022-10-14 13:54:32.186 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.254 (130 scanned)... 
[2022-10-14 13:54:32.187 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] GC Mem: 3813 kb, Working set / Private Mem: 64272 kb / 58736 kb, Handles: 290 
[2022-10-14 13:54:32.187 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.138 (131 scanned)... 
[2022-10-14 13:54:32.188 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.23 (132 scanned)... 
[2022-10-14 13:54:32.188 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.25 (132 scanned)... 
[2022-10-14 13:54:32.190 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.33 (134 scanned)... 
[2022-10-14 13:54:32.192 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.5 (135 scanned)... 
[2022-10-14 13:54:32.199 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.118 (136 scanned)... 
[2022-10-14 13:54:32.199 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.43 (137 scanned)... 
[2022-10-14 13:54:32.203 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : 132 addresses scanned - 40 ev.Discovered (100 probes active)... 
[2022-10-14 13:54:32.203 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.110 (138 scanned)... 
[2022-10-14 13:54:32.207 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.2 (139 scanned)... 
[2022-10-14 13:54:32.209 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.168 (140 scanned)... 
[2022-10-14 13:54:32.216 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.113 (143 scanned)... 
[2022-10-14 13:54:32.220 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.20 (144 scanned)... 
[2022-10-14 13:54:32.232 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.22 (145 scanned)... 
[2022-10-14 13:54:32.233 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.169 (147 scanned)... 
[2022-10-14 13:54:32.238 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.31 (148 scanned)... 
[2022-10-14 13:54:32.242 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.59 (150 scanned)... 
[2022-10-14 13:54:32.247 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.128 (153 scanned)... 
[2022-10-14 13:54:32.256 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.51 (154 scanned)... 
[2022-10-14 13:54:32.257 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.50 (155 scanned)... 
[2022-10-14 13:54:32.283 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.150 (156 scanned)... 
[2022-10-14 13:54:32.284 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.153 (157 scanned)... 
[2022-10-14 13:54:32.302 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.4 (158 scanned)... 
[2022-10-14 13:54:32.361 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.156 (160 scanned)... 
[2022-10-14 13:54:32.426 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.120 (161 scanned)... 
[2022-10-14 13:54:32.668 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.109 (162 scanned)... 
[2022-10-14 13:54:32.719 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 10.1.67.54 (163 scanned)... 
[2022-10-14 13:54:35.170 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : 165 addresses scanned - 65 ev.Discovered (91 probes active)... 
[2022-10-14 13:54:35.258 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 65 addresses. (256 scanned)... 
[2022-10-14 13:54:35.270 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Including gateway host address 172.19.0.3 
[2022-10-14 13:54:35.270 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Starting port scanning (0 probes active)... 
Unhandled exception. System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_WorkingSet64()
   at Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices.ProgressTimer(Action log)
   at Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices.<>c__DisplayClass14_2.<DiscoverServersAsync>b__6(Object _)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by marcschier** [comment]
#1763

**Comment by hansgschossmann** [comment]
@brentcocu-mayker pls verify with the latest release (see #1763 ). Please reactivate if the issue still exists.
