### ISSUE TITLE
All in one service can't access the keyvault

### ISSUE THREAD

**Issue by JaivyDaam** [Azure/Industrial-IoT#2018]
**Describe the bug**
After deploying the "All" infrastructure, I have been provided with a Keyvault, Managed Identity and an App service (Among others, but these are the relevant ones). Where the Web App wants to start but failed to start:
<details>
<summary>Stack Trace</summary>

```
2023-07-17T08:49:14.943349817Z at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2023-07-17T08:49:14.943353417Z at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2023-07-17T08:49:14.943360217Z at System.Threading.Tasks.Task`1.get_Result()
2023-07-17T08:49:14.943363817Z at
Microsoft.Extensions.Configuration.ConfigurationEx.AddFromKeyVault(IConfigurationBuilder builder, ConfigurationProviderPriority providerPriority, Boolean allowInteractiveLogon, Boolean singleton, String keyVaultUrlVarName) in
D:\a\1\s\common\src\Microsoft.Azure.IIoT.Auth.ActiveDirectory\src\Extensions\ConfigurationEx.cs:line 49
2023-07-17T08:49:14.943376817Z at Microsoft.Azure.IIoT.Services.All.Startup..ctor(IWebHostEnvironment env, IConfiguration configuration) in D:\a\1\s\services\src\Microsoft.Azure.IIoT.Services.All\src\Startup.cs:line 47
2023-07-17T08:49:14.943381217Z at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2023-07-17T08:49:14.943385417Z at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-07-17T08:49:14.943389217Z at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
2023-07-17T08:49:14.943393017Z at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
2023-07-17T08:49:14.943396717Z at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
2023-07-17T08:49:14.943400617Z at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
2023-07-17T08:49:14.943404617Z at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
2023-07-17T08:49:14.943408117Z at Microsoft.Extensions.Hosting.HostBuilder.Build()
2023-07-17T08:49:14.951236769Z at Microsoft.Azure.IIoT.Services.All.Program.Main(String[] args) in D:\a\1\s\services\src\Microsoft.Azure.IIoT.Services.All\src\Program.cs:line 26
2023-07-17T08:54:12.558792192Z Unhandled exception. System.AggregateException: One or more errors occurred. (A keyvault uri was provided could not access keyvault at the address. If you want to read configuration from keyvault, make sure the keyvault is reachable, the required permissions are configured on keyvault and authentication provider information is available. Sign into Visual Studio or Azure CLI on this machine and try again.)
2023-07-17T08:54:12.558863694Z ---> Microsoft.Azure.IIoT.Exceptions.InvalidConfigurationException: A keyvault uri was provided could not access keyvault at the address. If you want to read configuration from keyvault, make sure the keyvault is reachable, the required permissions are configured on keyvault and authentication provider information is available. Sign into Visual Studio or Azure CLI on this machine and try again.
2023-07-17T08:54:12.558870894Z ---> Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'Unauthorized'
2023-07-17T08:54:12.558875194Z at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2023-07-17T08:54:12.558879394Z at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String vaultBaseUrl, String secretName, CancellationToken cancellationToken)
2023-07-17T08:54:12.558990297Z at
Microsoft.Extensions.Configuration.ConfigurationEx.KeyVaultConfigurationProvider.ValidateReadSecretAsync(String secretName) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Auth.ActiveDirectory\src\Extensions\ConfigurationEx.cs:line 232
2023-07-17T08:54:12.558998097Z at
Microsoft.Extensions.Configuration.ConfigurationEx.KeyVaultConfigurationProvider.CreateInstanceAsync(IConfigurationRoot configuration, Boolean allowInteractiveLogon, String keyVaultUrlVarName, Boolean lazyLoad) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Auth.ActiveDirectory\src\Extensions\ConfigurationEx.cs:line 197
2023-07-17T08:54:12.559002897Z --- End of inner exception stack trace ---
2023-07-17T08:54:12.559010597Z at
Microsoft.Extensions.Configuration.ConfigurationEx.KeyVaultConfigurationProvider.CreateInstanceAsync(IConfigurationRoot configuration, Boolean allowInteractiveLogon, String keyVaultUrlVarName, Boolean lazyLoad) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Auth.ActiveDirectory\src\Extensions\ConfigurationEx.cs:line 200
2023-07-17T08:54:12.559015398Z at
Microsoft.Extensions.Configuration.ConfigurationEx.KeyVaultConfigurationProvider.CreateInstanceAsync(Boolean allowInteractiveLogon, Boolean singleton, IConfigurationRoot configuration, String keyVaultUrlVarName) in D:\a\1\s\common\src\Microsoft.Azure.IIoT.Auth.ActiveDirectory\src\Extensions\ConfigurationEx.cs:line 164
2023-07-17T08:54:12.559019798Z --- End of inner exception stack trace ---
```

</details> 

**To Reproduce**
1. Run the `deploy/scripts/deploy.ps1` `-type all`
2. Wait for the infrastructure to provision in the resource group
3. Watch the App Service Logs

**Expected behavior**
I expect that the WebApp starts without issue.

**Additional context**
Things I did:
- Checked the Web App, configuration settings are there and values match with resources provisioned.
- Checked the permissions of managed identity:
  - Key: Get,List,Sign,Unwrap key,Wrap Key, Create
  - Secret: Get,List,Set,Delete
  - Certificate: Get,List,Update,Create,Import
- Looked for a way to debug the All-in-one (I'm not a C# programmer :-) )

**Comment by marcschier** [comment]
I was not able to reproduce this, I ran a deployment using deploy and it runs through fine, I then tested the service manually using the CLI (on top of the .env file produced by the deployment script) and that also connected and kicked off a discovery run just fine.  Please send me deployment logs from the portal over email if this is continues for you.  It could be a resource limit in your subscription.
