### ISSUE TITLE
OPC Publisher - Unhandled error BadTimeout during Publish

### ISSUE THREAD

**Issue by MattCosturos** [Azure/Industrial-IoT#2231]
**Describe the bug**
OPC Publisher fails to publish any messages

**To Reproduce**
I am trying to use this module for the first time, so my setup is probably wrong. There are no example published_nodes.json files for 2.9, so I had to make up my own.

1. Deploy OPC Publisher module.
2. Configure opc publisher by editing the published_nodes.json file.
3. View module logs to see the publish fails.

Create Options from Deployment manifest
```
{
    "Hostname": "myHostName",
    "Cmd": [
        "-c",
        "--cl=5",
        "--PkiRootPath=/mount/pki",
        "--pf=/mount/published_nodes.json",
        "--lf=/mount/publisher.log",
        "--sl",
        "--ll=Debug",
        "--mm=PubSub",
        "--me=Json",
        "--fm=true",
        "--fd=false",
        "--bs=100",
        "--aa"
    ],
    "HostConfig": {
        "Binds": [
            "/path/to/my/files:/mount"
        ],
        "CapDrop": [
            "CHOWN",
            "SETUID"
        ]
    }
}
```

published_nodes.json
```
[
  {
    "EndpointUrl": "opc.tcp://my.server:1234",
    "DataSetWriterGroup": "ST38_114180",
    "DataSetWriterId": "ST38_114180_WriterId",
    "UseSecurity" : true,
    "OpcAuthenticationMode" : "UsernamePassword",
    "OpcAuthenticationUsername" : "myUsername",
    "OpcAuthenticationPassword" : "myPassword",
    "DataSetPublishingInterval" : "1000",
    "OpcNodes": [
      {
        "Id": "ns=2;s=ST38_114180.Path1.Controller_Mode",
        "OpcSamplingIntervalTimespan": "00:00:02",
        "OpcPublishingIntervalTimespan": "00:00:05",
        "HeartbeatIntervalTimespan": "00:01:00"
      },
      {
        "Id": "ns=2;s=ST38_114180.Path1.Feedrate_Override",
        "OpcSamplingIntervalTimespan": "00:00:02",
        "OpcPublishingIntervalTimespan": "00:00:05",
        "HeartbeatIntervalTimespan": "00:01:00"
      },
      {
        "Id" : "ns=2;s=ST38_114180.Path1.Rapid_Override",
        "OpcSamplingIntervalTimespan": "00:00:02",
        "OpcPublishingIntervalTimespan": "00:00:05",
        "HeartbeatIntervalTimespan": "00:01:00"
      }
    ]
  }
]
```
Error logs
```
 DIAGNOSTICS INFORMATION for          : ST38_114180
  # OPC Publisher Version (Runtime)    : 2.9.6.4+978a207cf9 (.NET 8.0.4/linux-x64/OPC Stack 1.5.374.36)
  # Time                               : 2024-05-29T16:10:21.0169799Z
  # Ingestion duration                 :    00:00:00:52 (dd:hh:mm:ss)
  # Endpoints connected/disconnected   :              1 | 0 (Connected)
  # Connection retries                 :              0
  # Subscriptions count                :              1
  # Good/Bad Monitored Items count     :              3 | 0
  # Queued/Minimum request count       :              3 | 3
  # Good/Bad Publish request count     :              3 | 0
  # Ingress value changes              :              3 (All time ~0.06/s; 3 in last 60s ~0.06/s)
  # Ingress events                     :              0 
  # Ingress values/events unassignable :              0
  # Server queue overflows             :              0 
  # Received Data Change Notifications :              1 (All time ~0.02/s; 1 in last 60s ~0.02/s)
  # Received Event Notifications       :              0 
  # Received Keep Alive Notifications  :              0 
  # Generated Cyclic read Notifications:              0 
  # Generated Heartbeat Notifications  :              0 
  # Generated Model Changes            :              0 
  # Notification batch buffer size     :              2
  # Encoder input/output buffer size   :              0 | 0
  # Encoder Notif. processed/dropped   :              0 | 0
  # Encoder Network Messages produced  :              0
  # Encoder avg Notifications/Message  :              0
  # Encoder worst Message split ratio  :              0
  # Encoder avg Message body size      :              0
  # Encoder avg Chunk (4 KB) usage     :              0
  # Estimated Chunks (4 KB) per day    :              0
  # Egress Messages queued/dropped     :              0 | 0
  # Egress Message send failures       :              0
  # Egress Messages successfully sent  :              0 

[24-05-29 16:10:23.0836] dbug: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaClient[0]
      Ensuring publish request count 2 is 3 requests.
[24-05-29 16:10:23.0860] info: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaStack[0]
      PUBLISH - Did not send another publish request. GoodPublishRequestCount=3, MinPublishRequestCount=3
[24-05-29 16:11:13.0797] dbug: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaClient[0]
      Ensuring publish request count 0 is 3 requests.
[24-05-29 16:11:13.0802] info: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaStack[0]
      PUBLISH - Did not send another publish request. GoodPublishRequestCount=3, MinPublishRequestCount=3
[24-05-29 16:11:13.0818] fail: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaStack[0]
      Publish #3, Reconnecting=False, Error: BadTimeout
[24-05-29 16:11:13.0818] fail: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaStack[0]
      Publish #4, Reconnecting=False, Error: BadTimeout
[24-05-29 16:11:13.1039] fail: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaStack[0]
      PUBLISH #4 - Unhandled error BadTimeout during Publish.
      Opc.Ua.ServiceResultException: BadTimeout
         at Opc.Ua.ClientBase.ValidateResponse(ResponseHeader header)
         at Opc.Ua.SessionClient.EndPublish(IAsyncResult result, UInt32& subscriptionId, UInt32Collection& availableSequenceNumbers, Boolean& moreNotifications, NotificationMessage& notificationMessage, StatusCodeCollection& results, DiagnosticInfoCollection& diagnosticInfos)
         at Opc.Ua.Client.Session.OnPublishComplete(IAsyncResult result)
[24-05-29 16:11:13.1039] fail: Azure.IIoT.OpcUa.Publisher.Stack.Services.OpcUaStack[0]
      PUBLISH #3 - Unhandled error BadTimeout during Publish.
      Opc.Ua.ServiceResultException: BadTimeout
         at Opc.Ua.ClientBase.ValidateResponse(ResponseHeader header)
         at Opc.Ua.SessionClient.EndPublish(IAsyncResult result, UInt32& subscriptionId, UInt32Collection& availableSequenceNumbers, Boolean& moreNotifications, NotificationMessage& notificationMessage, StatusCodeCollection& results, DiagnosticInfoCollection& diagnosticInfos)
         at Opc.Ua.Client.Session.OnPublishComplete(IAsyncResult result)


```

iotedge check output
```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.4.7 but 1.4.8 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
‼ host time is close to reference time - Warning
    Could not query NTP server
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
‼ aziot-edge package is up-to-date - Warning
    Installed IoT Edge daemon has version 1.4.27 but 1.4.33 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
28 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.
```

**Expected behavior**
I expect the opc messages to get published.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.6 LTS
- IOT Edge runtime 1.4 series
- OPC Publisher 2.9.6

**Comment by marcschier** [comment]
Timeout errors in log are not an issue, data seems to flow (3 value changes received, which are the initial values), since you use batch mode (--bs) the data will be sent onwards when the batch triggers.   Leave it running and if no data shows up, take a look at the troubleshoot.md file, but actually all looks good.

**Comment by MattCosturos** [comment]
Data does flow into the module, When I check my kepserver instance, the client count increases / decreases as expected when I start / stop this module. 

I'm a bit confused how a timeout during publish could not be an issue. My understand is the OPC publisher module subscribes to the nodes that are configured, and gets changes from the opc server. Then eventually it will publish those changes out as an IOT message. I assumed the BadTimeout during publish was indicating the outgoing messages failed to send.

I was monitoring the built in endpoint and never saw any messages. Nor did my other edge module receive any opc messages.

The routes in my deployment for reference.
```
               "opc-publisher-1-to-upstream": {
                        "route": "FROM /messages/modules/opc-publisher-1/* INTO $upstream"
                    },
                    "metrics": {
                        "priority": 2,
                        "route": "FROM /messages/modules/metrics/outputs/metricOutput INTO $upstream"
                    },
                    "opc-publisher-1-output-to-star-machines-inputFromOpc": {
                        "route": "FROM /messages/modules/opc-publisher-1/* INTO BrokeredEndpoint(\"/modules/star-machines/inputs/inputFromOpc\")"
                    }
```


In the metrics summary, there are 0 Egress messages, does that stat indicate writes to the opc server, or iot messages going out?


I will test without batch mode, and look at the troubleshooting guide as well

**Comment by MattCosturos** [comment]
Quick update to my previous comment.
I disabled batching `--bs=1` and `--bi=0` and now I see the Egress Message stats changing
```
 # Egress Messages queued/dropped     :             16 | 0
  # Egress Message send failures       :             33
  # Egress Messages successfully sent  :              0 
```

I'm also getting new errors, which is always fun.


```
  #47: Error 'One or more errors occurred. (Transient network error occurred, please retry.)' during sending network message. Retrying in 00:00:04.7000000...
      System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.)
       ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
       ---> System.Net.Sockets.SocketException (111): Connection refused
         at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
         at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
         at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.ConnectAsyncResult.End(IAsyncResult result)
         at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpIotTransport.InitializeAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIotConnector.OpenConnectionAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(IDeviceIdentity deviceIdentity, CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpUnit.EnsureSessionIsOpenAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpUnit.EnsureSessionIsOpenAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpUnit.OpenAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
         --- End of inner exception stack trace ---
         at Furly.Azure.IoT.Edge.Services.IoTEdgeHubSdkClient.ModuleClientAdapter.CreateAsync(String product, IotHubConnectionStringBuilder cs, String deviceId, String moduleId, ITransportSettings transportSetting, TimeSpan timeout, ILogger logger, IIoTEdgeClientState callback)
         at Furly.Azure.IoT.Edge.Services.IoTEdgeHubSdkClient.CreateAdapterAsync(IotHubConnectionStringBuilder cs, List`1 settings)
         --- End of inner exception stack trace ---
         at Furly.Azure.IoT.Edge.Services.IoTEdgeHubSdkClient.CreateAdapterAsync(IotHubConnectionStringBuilder cs, List`1 settings)
         at Furly.Azure.IoT.Edge.Services.IoTEdgeHubSdkClient.SendEventAsync(Message message, String output, CancellationToken ct)
         at Furly.Azure.IoT.Edge.Services.IoTEdgeEventClient.IoTEdgeMessage.SendAsync(CancellationToken ct)
         at Azure.IIoT.OpcUa.Publisher.Services.NetworkMessageSink.SendAsync(ValueTuple`2 message) in /home/vsts/work/1/s/src/Azure.IIoT.OpcUa.Publisher/src/Services/NetworkMessageSink.cs:line 250
```


There are no errors in edgeHub logs, and `iotedge check` shows all connections to the iothub are good for all protocols.

**Comment by MattCosturos** [comment]
Final update.
Error was self inflicted.
In the Create Options for the OPC Publisher module, I had `"Hostname" : "myHostName"` which was set the literal hostname of the actual edge device. I am not sure where I found that, I may have mis-understood something my coworker was doing. Once I removed that from the create options the module started publishing messages correctly.
