### ISSUE TITLE
Discovery result reported but not visible in the UI

### ISSUE THREAD

**Issue by vslepakov** [Azure/Industrial-IoT#395]
**Describe the bug**
discovery module was able to discover my opc-ua server and report the results back yo Azure but I cannot see any assets/endpoints in the engineering tool.

**To Reproduce**
1. Connect an Ubuntu VM with IoT Edge to IoT Hub
2. Run [opc-plc](https://github.com/Azure-Samples/iot-edge-opc-plc) using
`docker run -d --name opc-plc -p 50000:50000 -v /home/<username>/opc-plc:/appdata 
 mcr.microsoft.com/iotedge/op
c-plc:1 -aa`
3. As soon as all modules are deployed, activate scanning in the engineering tool
4. Wait till you see in the logs of discovery module that it discovered the server and reported the result back to Azure

**Expected behavior**
I see my asset and the endpoint in the engineering tool

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: Version: 80.0.3987.163 (Official Build) (64-bit)

**Additional context**
discovery module log:
```[10:52:07 WRN] Failed to add local host address. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices)
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Bool
ean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices.AddLoopbackAddressesAsync(List`1 addresses) in D:\a\1\s\component
s\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Edge.Discovery\src\Services\DiscoveryServices.cs:line 512
[10:52:07 INF] : Starting port scanning (0 probes active)... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:07 INF] Probe 31 : found OPC UA server at [::ffff:172.17.0.4]:50000 (protocol:0) ... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Servi
ces.DiscoveryServices)
[10:52:07 INF] : Found server 172.17.0.4:50000 (1656 scanned)... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:07 INF] Probe 0 : found OPC UA server at [::ffff:172.18.0.1]:50000 (protocol:0) ... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Servic
es.DiscoveryServices)
[10:52:07 INF] : Found server 172.18.0.1:50000 (1656 scanned)... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:07 INF] Probe 4 : found OPC UA server at [::ffff:172.18.0.3]:50000 (protocol:0) ... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Servic
es.DiscoveryServices)
[10:52:07 INF] : Found server 172.18.0.3:50000 (1656 scanned)... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:07 INF] Probe 375 : found OPC UA server at [::ffff:172.19.0.1]:50000 (protocol:0) ... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Serv
ices.DiscoveryServices)
[10:52:07 INF] : Found server 172.19.0.1:50000 (1656 scanned)... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:07 INF] : Found 4 ports on servers (1656 scanned)... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:07 INF] : Searching 4 discovery urls for endpoints... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:07 INF] : Trying to find endpoints on opc.tcp://172.18.0.1:50000/... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPubl
isher)
[10:52:08 INF] : Found 1 endpoints on opc.tcp://172.18.0.1:50000/. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:08 INF] : Trying to find endpoints on opc.tcp://industrial-edge.internal.cloudapp.net:50000/... (Microsoft.Azure.IIoT.OpcUa.Edge.Disc
overy.Services.ProgressPublisher)
[10:52:08 INF] : Found 1 endpoints on opc.tcp://industrial-edge.internal.cloudapp.net:50000/. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Ser
vices.ProgressPublisher)
[10:52:08 INF] : Trying to find endpoints on opc.tcp://172.18.0.3:50000/... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPubl
isher)
[10:52:08 INF] : Found 1 endpoints on opc.tcp://172.18.0.3:50000/. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:08 INF] : Trying to find endpoints on opc.tcp://172.19.0.1:50000/... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPubl
isher)
[10:52:08 INF] : Found 1 endpoints on opc.tcp://172.19.0.1:50000/. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:08 INF] : Found total of 1 servers ... (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)
[10:52:08 INF] Discovery took 00:00:25.4302853 and found 1 servers. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices)
[10:52:08 INF] Uploading 1 results...(Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices)
[10:52:08 INF] 1 results uploaded. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices)
[10:52:08 INF] : Discovery operation completed. (Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher)```

**Comment by dacolgit** [comment]
when the scan is finished you should have something like this in the Eng tool:

![image](https://user-images.githubusercontent.com/7942439/80229135-47e64380-8650-11ea-81c2-09f6a3c0f69a.png)

**Comment by vslepakov** [comment]
discovery is completed (module logs as above) but the "Scan Results" section is empty and there are no endpoints when I click on the discovery module name. happy to provide further logs if you need them.

**Comment by vslepakov** [comment]
no idea why, but it just started working after a couple of days.

**Comment by mwiot** [comment]
Hi, 

I am running 2.8.0 (all in one services, engineering tool and modules are the same version) and still experiencing the problem described in this post. How can I go about troubleshooting this?

The discovery is running a scan,  UA server is found and the log for the discovery module logs the line: 
`Uploading 2 results...`
`2 results uploaded.`

But in the engineering tool "Scan results" does not appear at all. 

![image](https://user-images.githubusercontent.com/82022527/138110092-5c2f9723-f858-4ee7-bf10-7ad5174cd91e.png)


It seems like the scan is running in the discovery module, and that the scan result is not reported back to the iot hub. 
If I run a scan and monitor the iot hub I see the scan settings being sent to the discovery module, but nothing is returned when results are uploaded from the discovery module to the iot hub. 

IOT hub monitoring of edge device while running discovery scan:

[IoTHubMonitor] [2:11:06 PM] Message received from [vm-opc-simulator4/discovery]:
{
  "version": 31,
  "properties": {
    "reported": {
      "Discovery": "Fast",
      "AddressRangesToScan": "10.0.0.0/24 [eth0];172.17.0.0/24 [docker0];172.18.0.0/24 [br-71fa168f9127]",
      "NetworkProbeTimeout": "00:00:03",
      "MaxNetworkProbes": null,
      "PortRangesToScan": "4840-4841;48000-48100;49320;50000;51200-51300;62222",
      "PortProbeTimeout": "00:00:05",
      "MaxPortProbes": null,
      "MinPortProbesPercent": null,
      "IdleTimeBetweenScans": "06:00:00",
      "DiscoveryUrls": null,
      "$metadata": {
        "$lastUpdated": "2021-10-20T14:11:06.4314849Z",
        "Discovery": {
          "$lastUpdated": "2021-10-20T14:11:06.4314849Z"
        },
        "AddressRangesToScan": {
          "$lastUpdated": "2021-10-20T14:11:06.4314849Z"
        },
        "NetworkProbeTimeout": {
          "$lastUpdated": "2021-10-20T14:11:06.4314849Z"
        },
        "MaxNetworkProbes": null,
        "PortRangesToScan": {
          "$lastUpdated": "2021-10-20T14:11:06.4314849Z"
        },
        "PortProbeTimeout": {
          "$lastUpdated": "2021-10-20T14:11:06.4314849Z"
        },
        "MaxPortProbes": null,
        "MinPortProbesPercent": null,
        "IdleTimeBetweenScans": {
          "$lastUpdated": "2021-10-20T14:11:06.4314849Z"
        },
        "DiscoveryUrls": null
      },
      "$version": 15
    }
  }
}

Discovery module log:

`
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Starting port scanning (0 probes active)...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Probe 368 : found OPC UA server at [::ffff:10.0.0.8]:50000 (protocol:0) ...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found server 10.0.0.8:50000 (519 scanned)...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Probe 742 : found OPC UA server at [::ffff:172.17.0.2]:50000 (protocol:0) ...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found server 172.17.0.2:50000 (1347 scanned)...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Probe 109 : found OPC UA server at [::ffff:172.17.0.1]:50000 (protocol:0) ...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found server 172.17.0.1:50000 (1864 scanned)...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Probe 58 : found OPC UA server at [::ffff:10.0.0.9]:50000 (protocol:0) ...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found server 10.0.0.9:50000 (2484 scanned)...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Probe 372 : found OPC UA server at [::ffff:172.18.0.1]:50000 (protocol:0) ...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found server 172.18.0.1:50000 (2484 scanned)...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 5 ports on servers (2484 scanned)...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Searching 5 discovery urls for endpoints...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Trying to find endpoints on opc.tcp://vm-opc-simulator4.internal.cloudapp.net:50000/...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 1 endpoints on opc.tcp://vm-opc-simulator4.internal.cloudapp.net:50000/.
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Trying to find endpoints on opc.tcp://172.17.0.2:50000/...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 1 endpoints on opc.tcp://172.17.0.2:50000/.
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Trying to find endpoints on opc.tcp://vm-opc-simulator4.local:50000/...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 1 endpoints on opc.tcp://vm-opc-simulator4.local:50000/.
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Trying to find endpoints on opc.tcp://vm-opc-simulator3.internal.cloudapp.net:50000/...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 2 endpoints on opc.tcp://vm-opc-simulator3.internal.cloudapp.net:50000/.
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Trying to find endpoints on opc.tcp://vm-opc-simulator4.local:50000/...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 2 endpoints on opc.tcp://vm-opc-simulator4.local:50000/.
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found total of 2 servers ...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Discovery took 00:00:24.3455651 and found 2 servers.
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Uploading 2 results...
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] 2 results uploaded.
[14:01:33 INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Discovery operation completed.
`
