### ISSUE TITLE
'BadEncodingLimitsExceeded ' received when creating subscriptions

### ISSUE THREAD

**Issue by jmbrunskill** [Azure/Industrial-IoT#55]
We have OPC Publisher 2.3.3 running on iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

On startup up of the Publisher we are getting a  'BadEncodingLimitsExceeded ' error.

How should we go about debugging/resolving this issue?

```
[04:34:04 INF] Publisher is running. Press CTRL-C to quit.
[04:34:04 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://10.70.64.95:49320'.
[04:34:06 INF] Create unsecured session for endpoint URI 'opc.tcp://10.70.64.95:49320' with timeout of 10000 ms.
[04:34:06 INF] Session successfully created with Id ns=1;g=73c5b05f-456f-49ec-a62b-a555657aaa6d.
[04:34:06 INF] The session to endpoint 'opc.tcp://10.70.64.95:49320/' has 3 entries in its namespace array:
[04:34:06 INF] Namespace index 0: http://opcfoundation.org/UA/
[04:34:06 INF] Namespace index 1: urn:NZS070HSTOPC01X.prod01.inroot.net:PTC.ThingWorxIC.1:UA%20Server
[04:34:06 INF] Namespace index 2: ThingWorx Industrial Connectivity
[04:34:06 INF] Created subscription with id 8 on endpoint 'opc.tcp://10.70.64.95:49320'
[04:34:06 INF] Create subscription on endpoint 'opc.tcp://10.70.64.95:49320' requested OPC publishing interval is 30000 ms. (revised: 30000 ms)
[04:34:06 INF] Start monitoring items on endpoint 'opc.tcp://10.70.64.95:49320'. Currently monitoring 0 items.
[04:34:06 INF] Now monitoring 10000 items in subscription with id '8'
[04:34:07 INF] Now monitoring 20000 items in subscription with id '8'
[04:34:08 INF] Now monitoring 30000 items in subscription with id '8'
[04:34:10 INF] Now monitoring 40000 items in subscription with id '8'
[04:34:14 INF] Now monitoring 50000 items in subscription with id '8'
[04:34:14 ERR] Unhandled OPC UA ServiceResultException 'BadEncodingLimitsExceeded 'Could not send request to server.'' when monitoring node 'ns=2;s=NZ070_Darfield_NZS070SRV01X.C270.NZ070_B05VA0506_AlmFault' on endpoint 'opc.tcp://10.70.64.95:49320'. Continue.
[04:34:14 INF] Now monitoring 60000 items in subscription with id '8'
[04:34:14 ERR] Unhandled OPC UA ServiceResultException 'BadEncodingLimitsExceeded 'Could not send request to server.'' when monitoring node 'ns=2;s=NZ070_Darfield_NZS070SRV01X.C801.NZ070_S1PW1P01_Msg1' on endpoint 'opc.tcp://10.70.64.95:49320'. Continue.
[04:34:15 ERR] Exception
Opc.Ua.ServiceResultException: Could not send request to server.
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.SessionClient.CreateMonitoredItems(RequestHeader requestHeader, UInt32 subscriptionId, TimestampsToReturn timestampsToReturn, MonitoredItemCreateRequestCollection itemsToCreate, MonitoredItemCreateResultCollection& results, DiagnosticInfoCollection& diagnosticInfos)
   at Opc.Ua.Client.Subscription.CreateItems()
   at Opc.Ua.Client.Subscription.ApplyChanges()
   at OpcPublisher.OpcSession.MonitorNodesAsync(CancellationToken ct) in /app/opcpublisher/OpcSession.cs:line 561
[04:34:25 INF] Start monitoring items on endpoint 'opc.tcp://10.70.64.95:49320'. Currently monitoring 66541 items.
[04:34:25 ERR] Unhandled OPC UA ServiceResultException 'BadEncodingLimitsExceeded 'Could not send request to server.'' when monitoring node 'ns=2;s=NZ070_Darfield_NZS070SRV01X.C270.NZ070_B05VA0506_AlmFault' on endpoint 'opc.tcp://10.70.64.95:49320'. Continue.
[04:34:25 ERR] Exception
Opc.Ua.ServiceResultException: Could not send request to server.
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.SessionClient.CreateMonitoredItems(RequestHeader requestHeader, UInt32 subscriptionId, TimestampsToReturn timestampsToReturn, MonitoredItemCreateRequestCollection itemsToCreate, MonitoredItemCreateResultCollection& results, DiagnosticInfoCollection& diagnosticInfos)
   at Opc.Ua.Client.Subscription.CreateItems()
   at Opc.Ua.Client.Subscription.ApplyChanges()
   at OpcPublisher.OpcSession.MonitorNodesAsync(CancellationToken ct) in /app/opcpublisher/OpcSession.cs:line 561
```

I have tried removing the tags that are reporting errors but it appears to just report the next tag as error'd after this. 

This error is also mentioned on 2 other OPC github projects. 
https://github.com/OPCFoundation/UA-.NET-Legacy/issues/107
https://github.com/open62541/open62541/issues/434

Neither is very clear to me why this might be happening, but sounds like it could be something going over the size limit for an OPCUA message?

**Comment by jmbrunskill** [comment]
@marcschier Yes, this use case is working now that we have the correct path.
We are seeing some performance challenges, I think it would be good to consider batching the OPC UA subscriptions if the resulting OPC UA group would result in a really large subscription.  Would be interesting to see if this would improve performance or reliability.
