### ISSUE TITLE
OpcPublisher module Basic256Sha256 communication issue

### ISSUE THREAD

**Issue by anipuramattom** [Azure/Industrial-IoT#728]
**Describe the bug**
secure communication session not created while trying to connect to Ignition Opc Server. Receives exception: 'Opc.Ua.ServiceResultException: BadSecureChannelClosed'. It works fine when securemode 'None' is enabled. 
I have added Ignition server certificate to trusted cert path.

**To Reproduce**
1. create pn.json with Server endpoint URL
2. Enable server security mode Basic256Sha256
3. restart opcpublisher and verify the secure connection establishment
4. when tried to add option: --tf = <server-cert-filename>, opc-publisher stops working.

**Expected behavior**
Opcpublisher should establish a session created with the server as shown below (in this case, it is unsecured, as secure option is 'None')
_[22:46:44 INF] Create unsecured session for endpoint URI 'opc.tcp://192.168.1.71:53530/OPCUA/SimulationServer' with timeout of 10000 ms.
[22:46:44 INF] Certificate 'DC=DESKTOP-1ETOHD3, O=Prosys OPC, CN=SimulationServer' will be trusted, since the autotrustservercerts options was specified.
[22:46:44 INF] Session successfully created with Id ns=1;g=c92c780c-e4f7-4b96-af34-717afbd283fe.
[22:46:44 INF] The session to endpoint 'opc.tcp://192.168.1.71:53530/OPCUA/SimulationServer' has 7 entries in its namespace array:_

**Screenshots**
**OpcPublisher Error Log:**
_IoTEdge detected.
[07:14:40 INF] Current directory is: /app
[07:14:40 INF] Log file is: opc-publisher-publisher.log
[07:14:40 INF] Log level is: info
[07:14:40 INF] OPC Publisher V2.5.3 starting up...
[07:14:40 INF] OPC UA monitored item notifications with one of the following 2 status codes will not generate telemetry events:
[07:14:40 INF] StatusCode: BadNoCommunication (dec: 2150694912, hex: 80310000)
[07:14:40 INF] StatusCode: BadWaitingForInitialData (dec: 2150760448, hex: 80320000)
[07:14:40 INF] opcstacktracemask set to: 0x0
[07:14:40 INF] OperationTimeout set to 120000
[07:14:40 INF] OPC UA server base address: opc.tcp://opc-publisher:62222/UA/Publisher
[07:14:40 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
[07:14:40 INF] Trusted Issuer store type is: Directory
[07:14:40 INF] Trusted Issuer Certificate store path is: pki/issuer
[07:14:40 INF] Trusted Peer Certificate store type is: Directory
[07:14:40 INF] Trusted Peer Certificate store path is: pki/trusted
[07:14:40 INF] Rejected certificate store type is: Directory
[07:14:40 INF] Rejected Certificate store path is: pki/rejected
[07:14:40 INF] Rejection of SHA1 signed certificates is disabled
[07:14:40 INF] Minimum certificate key size set to 1024
[07:14:40 INF] Application Certificate store type is: Directory
[07:14:40 INF] Application Certificate store path is: pki/own
[07:14:40 INF] Application Certificate subject name is: opc-publisher
[07:14:40 WRN] WARNING: Automatically accepting certificates. This is a security risk.
[07:14:40 INF] Application certificate with thumbprint 'FA61F84FEB5E96C892CBE32FB852E9DB2C058C2B' found in the application certificate store.
[07:14:40 INF] Application certificate is for ApplicationUri 'urn:opc-publisher:opc-publisher:microsoft:', ApplicationName 'opc-publisher' and Subject is 'opc-publisher'
[07:14:40 INF] Adding server certificate to trusted peer store. StorePath=pki/trusted
[07:14:40 WRN] **Can not add server certificate to trusted peer store**. Maybe it is already there.
System.ArgumentException: A certificate with the same thumbprint is already in the store.
   at Opc.Ua.DirectoryCertificateStore.Add(X509Certificate2 certificate, String password)
   at OpcPublisher.OpcApplicationConfiguration.InitApplicationSecurityAsync() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\OpcApplicationConfigurationSecurity.cs:line 240
[07:14:40 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
[07:14:40 INF] Trusted issuer store contains 0 certs
[07:14:40 INF] Trusted issuer store has 0 CRLs.
[07:14:40 INF] Trusted peer store contains 2 certs
[07:14:40 INF] 01: Subject 'C=US, S=CA, L=Folsom, OU="", O=Inductive Automation, CN=Ignition OPC UA Server' (thumbprint: 72580EA39968F61FB369C9781A41E4C9233F5C08)
[07:14:40 INF] 02: Subject 'CN=opc-publisher' (thumbprint: FA61F84FEB5E96C892CBE32FB852E9DB2C058C2B)
[07:14:40 INF] Trusted peer store has 0 CRLs.
[07:14:40 INF] Rejected certificate store contains 0 certs
[07:14:40 INF] There is no site configured.
[07:14:40 INF] Starting server on endpoint opc.tcp://opc-publisher:62222/UA/Publisher ...
[07:14:41 INF] Server started.
[07:14:41 INF] Attempting to load telemetry configuration file from: /appdata/telemetryconfiguration.json
[07:14:42 INF] The name of the configuration file for published nodes is: /appdata/pn.json
[07:14:42 INF] Attemtping to load node configuration from: /appdata/pn.json
[07:14:42 INF] Loaded 1 config file entry/entries.
[07:14:42 INF] There are 1 nodes to publish.
[07:14:42 INF] Create module client using 'Amqp_Tcp_Only' for communication.
[07:14:43 INF] IoTCentral mode: False
[07:14:43 INF] Connection status changed to 'Connected', reason 'Connection_Ok'
[07:14:44 INF] Message processing and hub communication configured with a send interval of 10 sec and a message buffer size of 225000 bytes.
[07:14:44 INF] Creating task process and batch monitored item data updates...
[07:14:44 INF]
[07:14:44 INF]
[07:14:44 INF] Publisher is running. Press CTRL-C to quit.
[07:14:44 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://10.0.0.5:62541'.
[07:14:44 ERR] Session creation to endpoint 'opc.tcp://10.0.0.5:62541' failed 1 time(s). Please verify if server is up and Publisher configuration is correct.
Opc.Ua.ServiceResultException: BadSecureChannelClosed
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcPublisher.OpcSession.ConnectSessionAsync(CancellationToken ct) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\OpcSession.cs:line 431_

**Error at the server side as below:**
"Error installing security token: StatusCode{name=Bad_SecurityChecksFailed, value=0x80130000, quality=bad}"
org.eclipse.milo.opcua.stack.core.UaException: no matching endpoint found: transportProfile=TCP_UASC_UABINARY, endpointUrl=opc.tcp://192.168.0.101:4096, securityPolicy=None, securityMode=None

_at org.eclipse.milo.opcua.stack.server.transport.uasc.UascServerAsymmetricHandler.lambda$openSecureChannel$3 (UascServerAsymmetricHandler.java:407)
at java.base/java.util.Optional.orElseThrow(Unknown Source)
at org.eclipse.milo.opcua.stack.server.transport.uasc.UascServerAsymmetricHandler.openSecureChannel (UascServerAsymmetricHandler.java:397)
at rg.eclipse.milo.opcua.stack.server.transport.uasc.UascServerAsymmetricHandler.lambda$sendOpenSecureChannelResponse$1 (UascServerAsymmetricHandler.java:301)
at org.eclipse.milo.opcua.stack.core.channel.SerializationQueue.lambda$encode$0(SerializationQueue.java:57)
at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$Task.run(ExecutionQueue.java:119)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)_

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 
 - Version :18.08

**Additional context**
When tried connect to same ignition server from freeopcua python module, by adding server certificate, it works fine.

**Comment by anipuramattom** [comment]
issue resolved by updating endpoint url by discovery server path:  'opc.tcp://<ip-addr>:4096/discovery'

When connecting with security option 'None', it works just with 'opc.tcp://<ip-addr>:4096'. But while adding Basic256Sha256, it is required to be given as 'opc.tcp://<ip-addr>:4096/**discovery**'
