### ISSUE TITLE
Cannot find publishednodes.json on Windows

### ISSUE THREAD

**Issue by terrymandin** [Azure/Industrial-IoT#741]
We installed IoT Edge on a Windows PC.  The OPC Publisher module is starting but it cannot see the publishednodes.json file.  We updated the "Binding" area to point to our file, but that did not resolve the issue.

publishednodes.json:
```
[
  {
    "EndpointUrl": "opc.tcp://<server>/OPCUA/SimulationServer",
    "UseSecurity": false,
    "OpcNodes": [
      {
        "Id": "ns=3;i=1001",
      },
      {
        "Id": "ns=3;i=1007",
      }
  },
]
```

Module configuration:
```
{
  "Hostname": "publisher",
  "Cmd": [
    "publisher",
    "--di=60",
    "--to",
    "ll=debug",
    "--aa",
    "--si",
    "0",
    "--ms",
    "4096",
    "--pf=./publishednodes.json"
  ],
  "HostConfig": {
    "Binds": [
      "c:/iiotedge:c:/appdata"
    ],
    "PortBindings": {
      "62222/tcp": [
        {
          "HostPort": "62222"
        }
      ]
    },
    "ExtraHosts": [
      "localhost:127.0.0.1"
    ]
  }
}
```

The file exists in c:\app.  We have confirmed that the file name is "publishednodes.json".  ie.  ".txt" is not appended.
![publishednodesloc](https://user-images.githubusercontent.com/833055/94574795-c616c980-0230-11eb-8605-be0850ef801b.jpg)

![publishednodesloc2](https://user-images.githubusercontent.com/833055/94584809-5f97a880-023c-11eb-8293-50df383d64c1.jpg)

Log is below. Note this entry: "The node configuration file './publishednodes.json' does not exist. Continue and wait for remote configuration requests."
```
[10:19:04 INF] Current directory is: C:\app
[10:19:04 INF] Log file is: publisher-publisher.log
[10:19:04 INF] Log level is: info
[10:19:04 INF] OPC Publisher V2.5.3 starting up...
[10:19:04 INF] OPC UA monitored item notifications with one of the following 2 status codes will not generate telemetry events:
[10:19:04 INF] StatusCode: BadNoCommunication (dec: 2150694912, hex: 80310000)
[10:19:04 INF] StatusCode: BadWaitingForInitialData (dec: 2150760448, hex: 80320000)
[10:19:04 INF] opcstacktracemask set to: 0x0
[10:19:04 INF] OperationTimeout set to 120000
[10:19:04 INF] OPC UA server base address: opc.tcp://publisher:62222/UA/Publisher
[10:19:04 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
[10:19:04 INF] Trusted Issuer store type is: Directory
[10:19:04 INF] Trusted Issuer Certificate store path is: pki/issuer
[10:19:04 INF] Trusted Peer Certificate store type is: Directory
[10:19:04 INF] Trusted Peer Certificate store path is: pki/trusted
[10:19:04 INF] Rejected certificate store type is: Directory
[10:19:04 INF] Rejected Certificate store path is: pki/rejected
[10:19:04 INF] Rejection of SHA1 signed certificates is disabled
[10:19:04 INF] Minimum certificate key size set to 1024
[10:19:04 INF] Application Certificate store type is: Directory
[10:19:04 INF] Application Certificate store path is: pki/own
[10:19:04 INF] Application Certificate subject name is: publisher
[10:19:04 WRN] WARNING: Automatically accepting certificates. This is a security risk.
[10:19:04 INF] Application certificate with thumbprint '3E9A51A0C54C2684220655276538BC907794B580' found in the application certificate store.
[10:19:04 INF] Application certificate is for ApplicationUri 'urn:publisher:publisher:microsoft:', ApplicationName 'publisher' and Subject is 'publisher'
[10:19:04 INF] Adding server certificate to trusted peer store. StorePath=pki/trusted
[10:19:04 WRN] Can not add server certificate to trusted peer store. Maybe it is already there.
System.ArgumentException: A certificate with the same thumbprint is already in the store.
   at Opc.Ua.DirectoryCertificateStore.Add(X509Certificate2 certificate, String password)
   at OpcPublisher.OpcApplicationConfiguration.InitApplicationSecurityAsync() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\OpcApplicationConfigurationSecurity.cs:line 240
[10:19:04 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
[10:19:04 INF] Trusted issuer store contains 0 certs
[10:19:04 INF] Trusted issuer store has 0 CRLs.
[10:19:04 INF] Trusted peer store contains 1 certs
[10:19:04 INF] 01: Subject 'CN=publisher' (thumbprint: 3E9A51A0C54C2684220655276538BC907794B580)
[10:19:04 INF] Trusted peer store has 0 CRLs.
[10:19:04 INF] Rejected certificate store contains 0 certs
[10:19:04 INF] There is no site configured.
[10:19:04 INF] Starting server on endpoint opc.tcp://publisher:62222/UA/Publisher ...
[10:19:05 INF] Server started.
[10:19:05 INF] Using default telemetry configuration.
[10:19:05 INF] The name of the configuration file for published nodes is: ./publishednodes.json
[10:19:05 INF] The node configuration file './publishednodes.json' does not exist. Continue and wait for remote configuration requests.
[10:19:05 INF] There are 0 nodes to publish.
[10:19:05 INF] Create module client using 'Amqp_Tcp_Only' for communication.
[10:19:05 INF] IoTCentral mode: False
[10:19:26 ERR] Connection status changed to 'Disconnected', reason 'Retry_Expired'
[10:19:27 INF] Connection status changed to 'Connected', reason 'Connection_Ok'
[10:19:27 INF] Message processing and hub communication configured with a send interval of 0 sec and a message buffer size of 4096 bytes.
```

**Comment by terrymandin** [comment]
Was able to resolve the issue with help from a colleague.  Setting the "pf" parameter to point to the directory that publishednodes.json fixed the issue:

```
{
  "Hostname": "publisher",
  "Cmd": [
    "publisher",
    "--di=60",
    "--to",
    "--aa",
    "--si",
    "0",
    "--ms",
    "4096",
    "--pf=c:/appdata/publishednodes.json"
  ],
  "HostConfig": {
    "Binds": [
      "c:/iiotedge:c:/appdata"
    ],
    "PortBindings": {
      "62222/tcp": [
        {
          "HostPort": "62222"
        }
      ]
    },
    "ExtraHosts": [
      "localhost:127.0.0.1"
    ]
  }
}
'''
