### ISSUE TITLE
"Failed to add local host address" exception in Discovery service

### ISSUE THREAD

**Issue by terrymandin** [Azure/Industrial-IoT#743]
I iinstalled the Industrial IIoT Platform v2.5.58.  The Windows gateway Discovery module is not finding any OPC Servers or endpoints - none are visible in the UI.  When I looked at the IoT Edge "Discovery" module I found the following Exception:

```
[2020-09-30 18:51:09Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Starting port scanning (0 probes active)...
[2020-09-30 18:51:10Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 0 ports on servers (207 scanned)...
[2020-09-30 18:51:10Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Uploading 0 results...
[2020-09-30 18:51:10Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] 0 results uploaded.
[2020-09-30 18:51:10Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Discovery operation completed.
[2020-09-30 18:55:57Z INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] New settings processed.
[2020-09-30 18:56:16Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Discovery operation started.
[2020-09-30 18:56:16Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Start Fast discovery run...
[2020-09-30 18:56:16Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Starting network scan (0 probes active)...
[2020-09-30 18:56:16Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Start scanning ["172.31.160.1/32", "172.31.175.0/24 [vEthernet (Ethernet) 3]"]...
[2020-09-30 18:56:16Z INF Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost] New settings processed.
[2020-09-30 18:56:16Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found address 172.31.175.56 (0 scanned)...
[2020-09-30 18:56:19Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] GC Mem: 15771 kb, Working set / Private Mem: 78824 kb / 50860 kb, Handles: 777
[2020-09-30 18:56:19Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : 199 addresses scanned - 1 ev.Discovered (58 probes active)...
[2020-09-30 18:56:20Z INF Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.ProgressPublisher] : Found 1 addresses. (257 scanned)...
[2020-09-30 18:56:20Z WRN Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices] Failed to add local host address.
System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.IIoT.OpcUa.Edge.Discovery.Services.DiscoveryServices.AddLoopbackAddressesAsync(List`1 addresses) in D:\a\1\s\components\opc-ua\src\Microsoft.Azure.IIoT.OpcUa.Edge.Discovery\src\Services\DiscoveryServices.cs:line 518
```

**Comment by marcschier** [comment]
Fixed in 2.8.0
