### ISSUE TITLE
Unsupported transport profile

### ISSUE THREAD

**Issue by AlbertoCruzHidalga** [Azure/Industrial-IoT#828]
**Describe the bug**
We are trying to connect OpcUA Publisher with a PCS7 OPC UA server with [None, None] SecurityMode. The server is reachable and we are able to connect with other clients. With OPC UA publisher we got this error :

 Session creation to endpoint 'opc.tpc://....' failed 9084 time(s). Please verify if server is up and Publisher configuration is correct.
Opc.Ua.ServiceResultException: Unsupported transport profile
```
   at Opc.Ua.WcfChannelBase.CreateUaBinaryChannel(ApplicationConfiguration configuration, EndpointDescription description, EndpointConfiguration endpointConfiguration, X509Certificate2 clientCertificate, X509Certificate2Collection clientCertificateChain, ServiceMessageContext messageContext)
   at Opc.Ua.WcfChannelBase.CreateUaBinaryChannel(ApplicationConfiguration configuration, EndpointDescription description, EndpointConfiguration endpointConfiguration, X509Certificate2 clientCertificate, ServiceMessageContext messageContext)
   at Opc.Ua.DiscoveryChannel.Create(Uri discoveryUrl, EndpointConfiguration endpointConfiguration, ServiceMessageContext messageContext, X509Certificate2 clientCertificate)
   at Opc.Ua.DiscoveryClient.Create(Uri discoveryUrl, EndpointConfiguration endpointConfiguration, ApplicationConfiguration applicationConfiguration)
   at Opc.Ua.DiscoveryClient.Create(Uri discoveryUrl, EndpointConfiguration configuration)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcPublisher.OpcSession.ConnectSessionAsync(CancellationToken ct) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\OpcSession.cs:line 431
[15:51:11 INF] Connect and monitor session and nodes on endpoint 'opc.tpc://....'.
[15:51:11 ERR] Session creation to endpoint 'opc.tpc://...' failed 9085 time(s). Please verify if server is up and Publisher configuration is correct.
Opc.Ua.ServiceResultException: Unsupported transport profile

   at Opc.Ua.WcfChannelBase.CreateUaBinaryChannel(ApplicationConfiguration configuration, EndpointDescription description, EndpointConfiguration endpointConfiguration, X509Certificate2 clientCertificate, X509Certificate2Collection clientCertificateChain, ServiceMessageContext messageContext)
   at Opc.Ua.WcfChannelBase.CreateUaBinaryChannel(ApplicationConfiguration configuration, EndpointDescription description, EndpointConfiguration endpointConfiguration, X509Certificate2 clientCertificate, ServiceMessageContext messageContext)
   at Opc.Ua.DiscoveryChannel.Create(Uri discoveryUrl, EndpointConfiguration endpointConfiguration, ServiceMessageContext messageContext, X509Certificate2 clientCertificate)
   at Opc.Ua.DiscoveryClient.Create(Uri discoveryUrl, EndpointConfiguration endpointConfiguration, ApplicationConfiguration applicationConfiguration)
   at Opc.Ua.DiscoveryClient.Create(Uri discoveryUrl, EndpointConfiguration configuration)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcPublisher.OpcSession.ConnectSessionAsync(CancellationToken ct) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\OpcSession.cs:line 431
```

**To Reproduce**
1. restart OpcuaPublisher and got the above error

**Expected behavior**
OpcUa Publisher should be able to connect with  PCS7 OPC UA server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 IoT Enterprise
 - Browser N/A

**Additional context**

**Comment by mregen** [comment]
Hi @AlbertoCruzHidalga, the fix should be simple: There is a typo in the url: Instead of `opc.tpc` it must be `opc.tcp`.
Please let me know if this is the issue.

Thanks,
Martin
