### ISSUE TITLE
OPC Publisher as Module not working since version 2.4

### ISSUE THREAD

**Issue by tbn-mm** [Azure/Industrial-IoT#93]
**Describe the bug**
Since version 2.4, the publisher isn't working (Publisher stops) as an IoT Edge Module like described [here](https://github.com/Azure/Industrial-IoT/blob/master/docs/modules/publisher.md#using-it-as-a-module-in-azure-iot-edge).

**To Reproduce**
Follow the [docs](https://github.com/Azure/Industrial-IoT/blob/master/docs/modules/publisher.md#using-it-as-a-module-in-azure-iot-edge) and set `<tag>` to 2.4 or 2.5. The publisher will exit. Set `<tag>` to 2.3 and it keeps running like expected. So broken somewhere between 2.3.3 and 2.4.

**Expected behavior**
Publisher should be able to work as an IoT Edge Module **without** providing a device or hub connection string (that's what the error message says, but that's not the correct solution).

**Desktop (please complete the following information):**
Tested with iotedgehubdev on windows with linux containers.

**Additional context**
Log for version 2.5.1:
```
publisher             | [10:49:43 INF] Current directory is: /app
publisher             | [10:49:43 INF] Log file is: publisher-publisher.log
publisher             | [10:49:43 INF] Log level is: info
publisher             | [10:49:43 INF] OPC Publisher V2.5.1 starting up...
publisher             | [10:49:43 INF] OPC UA monitored item notifications with one of the following 2 status codes will not generate telemetry events:
publisher             | [10:49:43 INF] StatusCode: BadNoCommunication (dec: 2150694912, hex: 80310000)
publisher             | [10:49:43 INF] StatusCode: BadWaitingForInitialData (dec: 2150760448, hex: 80320000)
publisher             | [10:49:43 INF] opcstacktracemask set to: 0x0
publisher             | [10:49:43 INF] OperationTimeout set to 120000
publisher             | [10:49:43 INF] OPC UA server base address: opc.tcp://publisher:62222/UA/Publisher
publisher             | [10:49:43 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
publisher             | [10:49:43 INF] Trusted Issuer store type is: Directory
publisher             | [10:49:43 INF] Trusted Issuer Certificate store path is: pki/issuer
publisher             | [10:49:43 INF] Trusted Peer Certificate store type is: Directory
publisher             | [10:49:43 INF] Trusted Peer Certificate store path is: pki/trusted
publisher             | [10:49:43 INF] Rejected certificate store type is: Directory
publisher             | [10:49:43 INF] Rejected Certificate store path is: pki/rejected
publisher             | [10:49:43 INF] Rejection of SHA1 signed certificates is disabled
publisher             | [10:49:43 INF] Minimum certificate key size set to 1024
publisher             | [10:49:43 INF] Application Certificate store type is: Directory
publisher             | [10:49:43 INF] Application Certificate store path is: pki/own
publisher             | [10:49:43 INF] Application Certificate subject name is: publisher
publisher             | [10:49:43 WRN] WARNING: Automatically accepting certificates. This is a security risk.
publisher             | [10:49:43 INF] Application certificate with thumbprint '9692758182E47670A37D76DD6FA84449B4072F02' found in the application certificate store.
publisher             | [10:49:43 INF] Application certificate is for ApplicationUri 'urn:publisher:publisher:microsoft:', ApplicationName 'publisher' and Subject is 'publisher'
publisher             | [10:49:43 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
publisher             | [10:49:43 INF] Trusted issuer store contains 0 certs
publisher             | [10:49:43 INF] Trusted issuer store has 0 CRLs.
publisher             | [10:49:43 INF] Trusted peer store contains 0 certs
publisher             | [10:49:43 INF] Trusted peer store has 0 CRLs.
publisher             | [10:49:43 INF] Rejected certificate store contains 0 certs
publisher             | [10:49:43 INF] There is no site configured.
publisher             | [10:49:43 INF] Starting server on endpoint opc.tcp://publisher:62222/UA/Publisher ...
publisher             | [10:49:44 INF] Server started.
publisher             | [10:49:44 INF] Using default telemetry configuration.
publisher             | [10:49:44 INF] IoT Hub owner connection string not passed as argument.
publisher             | [10:49:44 INF] IoTHub device cert store type is: X509Store
publisher             | [10:49:44 INF] IoTHub device cert path is: My
publisher             | [10:49:44 INF] IoT Hub owner connection string not specified. Assume device connection string already in cert store or passed in via command line option.
publisher             | [10:49:44 INF] Attempting to read device connection string from cert store using subject name: publisher
publisher             | [10:49:44 FTL] Device connection string not found in secure store. Please pass it in at least once via command line option. Can not connect to IoTHub. Exiting...
publisher             | [10:49:44 FTL]    at OpcPublisher.IotHubCommunication..ctor() in D:\a\1\s\modules\opc-publisher\opcpublisher\IotHubCommunication.cs:line 157
publisher             |    at OpcPublisher.IotHubCommunication.get_Instance() in D:\a\1\s\modules\opc-publisher\opcpublisher\IotHubCommunication.cs:line 62
publisher             |    at OpcPublisher.Program.MainAsync(String[] args) in D:\a\1\s\modules\opc-publisher\opcpublisher\Program.cs:line 736
publisher             | System.ArgumentException: Device connection string not found in secure store. Please pass it in at least once via command line option. Can not connect to IoTHub. Exiting...
publisher             |    at OpcPublisher.IotHubCommunication..ctor() in D:\a\1\s\modules\opc-publisher\opcpublisher\IotHubCommunication.cs:line 157
publisher             |    at OpcPublisher.IotHubCommunication.get_Instance() in D:\a\1\s\modules\opc-publisher\opcpublisher\IotHubCommunication.cs:line 62
publisher             |    at OpcPublisher.Program.MainAsync(String[] args) in D:\a\1\s\modules\opc-publisher\opcpublisher\Program.cs:line 736
publisher             | [10:49:44 FTL] Publisher exiting...
```

Log for version 2.3.3:
```
publisher             | IoTEdge detected.
publisher             | [10:54:38 INF] Current directory is: /appdata
publisher             | [10:54:38 INF] Log file is: publisher-publisher.log
publisher             | [10:54:38 INF] Log level is: info
publisher             | [10:54:38 INF] OPC Publisher V2.3.3 starting up...
publisher             | [10:54:38 INF] OPC UA monitored item notifications with one of the following 2 status codes will not generate telemetry events:
publisher             | [10:54:38 INF] StatusCode: BadNoCommunication (dec: 2150694912, hex: 80310000)
publisher             | [10:54:38 INF] StatusCode: BadWaitingForInitialData (dec: 2150760448, hex: 80320000)
publisher             | [10:54:38 INF] opcstacktracemask set to: 0x0
publisher             | [10:54:38 INF] OperationTimeout set to 120000
publisher             | [10:54:38 INF] OPC UA server base address: opc.tcp://publisher:62222/UA/Publisher
publisher             | [10:54:38 INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
publisher             | [10:54:38 INF] Trusted Issuer store type is: Directory
publisher             | [10:54:38 INF] Trusted Issuer Certificate store path is: pki/issuer
publisher             | [10:54:38 INF] Trusted Peer Certificate store type is: Directory
publisher             | [10:54:38 INF] Trusted Peer Certificate store path is: pki/trusted
publisher             | [10:54:38 INF] Rejected certificate store type is: Directory
publisher             | [10:54:38 INF] Rejected Certificate store path is: pki/rejected
publisher             | [10:54:38 INF] Rejection of SHA1 signed certificates is disabled
publisher             | [10:54:38 INF] Minimum certificate key size set to 1024
publisher             | [10:54:38 INF] Application Certificate store type is: Directory
publisher             | [10:54:38 INF] Application Certificate store path is: pki/own
publisher             | [10:54:38 INF] Application Certificate subject name is: publisher
publisher             | [10:54:38 WRN] WARNING: Automatically accepting certificates. This is a security risk.
publisher             | [10:54:38 INF] No existing Application certificate found. Create a self-signed Application certificate valid from yesterday for 12 months,
publisher             | [10:54:38 INF] with a 2048 bit key and 256 bit hash.
publisher             | [10:54:39 INF] Application certificate with thumbprint '636E9DB05C2C668150BD211AF0D79BC9C6A14CA5' created.
publisher             | [10:54:39 INF] Application certificate is for ApplicationUri 'urn:publisher:publisher:microsoft:', ApplicationName 'publisher' and Subject is 'publisher'
publisher             | [10:54:39 INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
publisher             | [10:54:39 INF] Trusted issuer store contains 0 certs
publisher             | [10:54:39 INF] Trusted issuer store has 0 CRLs.
publisher             | [10:54:39 INF] Trusted peer store contains 0 certs
publisher             | [10:54:39 INF] Trusted peer store has 0 CRLs.
publisher             | [10:54:39 INF] Rejected certificate store contains 0 certs
publisher             | [10:54:39 INF] There is no site configured.
publisher             | [10:54:39 INF] Starting server on endpoint opc.tcp://publisher:62222/UA/Publisher ...
publisher             | [10:54:39 INF] Server started.
publisher             | [10:54:39 INF] Using default telemetry configuration.
publisher             | [10:54:39 INF] The name of the configuration file for published nodes is: /tmp/publishfile.json
publisher             | [10:54:39 INF] Attemtping to load node configuration from: /tmp/publishfile.json
publisher             | [10:54:40 INF] There are 0 nodes to publish.
publisher             | [10:54:40 INF] Protocol used for IoT EdgeHub communication is'Amqp_Tcp_Only'
publisher             | [10:54:40 INF] IoTCentral mode: False
publisher             | [10:54:41 INF] Connection status changed to 'Connected', reason 'Connection_Ok'
publisher             | [10:54:41 INF] Message processing and hub communication configured with a send interval of 10 sec and a message buffer size of 262144 bytes.
publisher             | [10:54:41 INF] Creating task process and batch monitored item data updates...
publisher             | [10:54:41 INF] 
publisher             | [10:54:41 INF] 
publisher             | [10:54:41 INF] Publisher is running. Press CTRL-C to quit.
```

**Comment by perttvil** [comment]
@tbn-mm were you able to fix the iotedgehubdev issue? 
I'm currently having the same problem.

**Comment by tbn-mm** [comment]
@perttvil No, but haven't tried for over a year.
